#ifndef __MAPDEF_H
#define __MAPDEF_H

#include <Mapping/MappingSdk.h>

static FIELD_POSITION	MAPEDIT_DEFAULTPOS = {
	FIELD_POS_UNFIXED,
	FIELD_POS_UNFIXED,
};
#define LPMAPEDIT_DEFAULTPOS	NULL

#define MAPEDIT_TYPENAME_LEN	30
typedef struct _MAPEDIT_TYPEVAL {
	TCHAR				name[MAPEDIT_TYPENAME_LEN];		///< Nom du champ
	BOOL				canUpdateLen;					///< La taille du champ est elle modifiable ?
	WORD				subTypeListLen;					///< Nombre de sous-types ou 0
	INT					iconID;							///< Icone à l'affichage
	_MAPEDIT_TYPEVAL	*subTypeList;					///< Liste des sous types ou NULL
	FIELD_PROPERTY		defaultFieldExVal;				///< Valeur par défaut pour une entrée
} MAPEDIT_TYPEVAL;

#define MAPEDITTYPE_BEGIN( mapName,	elmtCount	)																		static MAPEDIT_TYPEVAL	mapName [ elmtCount] = {
																															//	name	canUpdateLen	subTypeListLen		iconID	subTypeList		type	subType		len		bVirtual	bReadOnly	defVal	bNeeded	bNegLogic	bResetToMax
#define MAPEDITTYPE_DECLARE_SUBTYPE(	szName,	bCanUpdateLen,	type,	subType, len)										{szName,	bCanUpdateLen,	0,					0,		NULL,			{type,	subType,	len,	FALSE,		FALSE,		0,		FALSE,	FALSE,		FALSE	}},	
#define MAPEDITTYPE_DECLARE_TYPE(		szName,	bCanUpdateLen,	iconId,	type,	len)										{szName,	bCanUpdateLen,	0,					iconId,	NULL,			{type,	0,			len,	FALSE,		FALSE,		0,		FALSE,	FALSE,		FALSE	}},	
#define MAPEDITTYPE_DECLARE_TYPELIST(	szName,	bCanUpdateLen,	iconId,	type,	len, subTypeList,	subTypeListCount)		{szName,	bCanUpdateLen,	subTypeListCount,	iconId,	subTypeList,	{type,	0,			len,	FALSE,		FALSE,		0,		FALSE,	FALSE,		FALSE	}},	
#define MAPEDITTYPE_END()																								};


MAPEDITTYPE_BEGIN(	MAPEDIT_TYPEDATE_LIST,	TYPEDATE_COUNT)
	/* DATE_ISO			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Iso"),					TRUE,	TYPE_DATE, DATE_ISO,		8	)
	/* DATE_545			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("5-4-5"),				FALSE,	TYPE_DATE, DATE_545,		14	)
	/* DATE_HEURE		*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("DateTime"),				TRUE,	TYPE_DATE, DATE_HEURE,		8	)
	/* DATE_ROULANTE	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Roulante"),				TRUE,	TYPE_DATE, DATE_ROULANTE,	8	)
	/* DATE_C			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("DateC"),				FALSE,	TYPE_DATE, DATE_C,			14	)
	/* DATE_F			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("DateF"),				FALSE,	TYPE_DATE, DATE_F,			32	)
	/* HEURE_1			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Time1"),				FALSE,	TYPE_DATE, HEURE_1,			8	)
	/* HEURE_2			*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Time2"),				FALSE,	TYPE_DATE, HEURE_2,			11	)
	/* DATE_MINUTE		*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("DateMinute"),			TRUE,	TYPE_DATE, DATE_MINUTE,		20	)
	/* HEURE_2HALF		*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Time3"),				TRUE,	TYPE_DATE, HEURE_2HALF,		10	)
	/* HEURE_QUARTER	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Time4"),				TRUE,	TYPE_DATE, HEURE_4,			7	)
	/* DATE_CVF_DELTA	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Delta sur Dfv Carte"),	TRUE,	TYPE_DATE, DATE_CVF_DELTA,	10	)
	/* DATE_TIME_REAL	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("DateTimeReal"),			FALSE,	TYPE_DATE, DATE_TIME_REAL,	30	)
	/* DATE_NDOT		*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("NDot Date"),			FALSE,	TYPE_DATE, DATE_NDOT,		24	)
	/* DATE_TIME_NDOT	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("NDot DateTime"),		FALSE,	TYPE_DATE, DATE_TIME_NDOT,	40	)
	/* DATE_ISO1999		*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Iso1999"),				TRUE,	TYPE_DATE, DATE_ISO1999,	15	)
	/* DATE_MK3			*/  MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Mk31989"),				TRUE,	TYPE_DATE, DATE_MK3,		24	)
MAPEDITTYPE_END()

MAPEDITTYPE_BEGIN(	MAPEDIT_TYPENOMBRE_LIST,	TYPENOMBRE_COUNT)
	/* NOMBRE_UNSIGNED_INTEGER	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Unsigned Integer"),		TRUE,	TYPE_NOMBRE, NOMBRE_UNSIGNED_INTEGER,	8	)
	/* NOMBRE_SIGNED_INTEGER	*/	MAPEDITTYPE_DECLARE_SUBTYPE(	_T("Signed Integer"),		TRUE,	TYPE_NOMBRE, NOMBRE_SIGNED_INTEGER,		8	)
MAPEDITTYPE_END()

MAPEDITTYPE_BEGIN(	MAPEDIT_TYPE_LIST,	TYPE_COUNT)
	/* TYPE_NOMBRE		*/	MAPEDITTYPE_DECLARE_TYPELIST(	_T("Number"),			TRUE,	0 /*IDI_ICON_NUMBER */,		TYPE_NOMBRE,		0,	MAPEDIT_TYPENOMBRE_LIST,	TYPENOMBRE_COUNT)
	/* TYPE_BOOLEEN		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Boolean"),			TRUE,	0 /*IDI_ICON_BOOL */,		TYPE_BOOLEEN,		1	)
	/* TYPE_DATE		*/	MAPEDITTYPE_DECLARE_TYPELIST(	_T("Date"),				TRUE,	0 /*IDI_ICON_DATE */,		TYPE_DATE,			8,	MAPEDIT_TYPEDATE_LIST,	TYPEDATE_COUNT	)
	/* TYPE_PLANNING	*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Planning Hebdo."),	FALSE,	0 /*IDI_ICON_NULL */,		TYPE_PLANNING,		14	)
	/* TYPE_TRANSCARTE	*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Num. Transcarte"),	TRUE,	0 /*IDI_ICON_NULL */,		TYPE_TRANSCARTE,	16	)
	/* TYPE_DATA		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Data"),				TRUE,	0 /*IDI_ICON_DATA */,		TYPE_DATA,			0	)
	/* TYPE_BITMAP		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Bitmap"),			TRUE,	0 /*IDI_ICON_BITMAP */,		TYPE_BITMAP,		0	)
	/* TYPE_SWITCH		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Switch"),			TRUE,	0 /*IDI_ICON_SWITCH */,		TYPE_SWITCH,		0	)
	/* TYPE_CASE		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Case"),				TRUE,	0 /*IDI_ICON_CASE*/,		TYPE_CASE,			0	/*,	MAPEDIT_TYPETEST_LIST,	TEST_LEN	*/	)
	/* TYPE_TEXTE		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Text"),				TRUE,	0 /*IDI_ICON_TEXT */,		TYPE_TEXTE,			32	)
	/* TYPE_CONST		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Constant"),			TRUE,	0 /*IDI_ICON_CONST*/,		TYPE_CONST,			8	)
	/* TYPE_LIST		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("List"),				TRUE,	0 /*IDI_ICON_LIST*/,		TYPE_LIST,			0	)
	/* TYPE_LIST2		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("[Israel] Liste2"),	TRUE,	0 /*IDI_ICON_LIST*/,		TYPE_LIST2,			0	)
	/* TYPE_PADDING		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Padding"),			TRUE,	0 /*IDI_ICON_LIST*/,		TYPE_PADDING,		0	)
	/* TYPE_DATA_FIELD	*/	MAPEDITTYPE_DECLARE_TYPE(		_T("DataField"),		TRUE,	0 /*IDI_ICON_DATA */,		TYPE_DATA_FIELD,	0	)
	/* TYPE_UNION		*/	MAPEDITTYPE_DECLARE_TYPE(		_T("Union"),			TRUE,	0 /*IDI_ICON_DATA */,		TYPE_UNION,			0	)
MAPEDITTYPE_END()

#define MAPEDIT_FIELDTYPENAME_LEN	50
typedef struct _MAPEDIT_FIELDTYPEINFO {
	TCHAR				szName[MAPEDIT_FIELDTYPENAME_LEN];	///< Nom du type de champ mapping (contrat, profil...)
	MAP_FIELDS_IDTYPE	typeId;								///< Identifiant du type
} MAPEDIT_FIELDTYPEINFO;

#define MAPEDITFIELDTYPE_BEGIN( mapName )					static MAPEDIT_FIELDTYPEINFO mapName [] = {
																//	szName		typeId
#define MAPEDITFIELDTYPE_DECLARE( szName,	typeId )			{	szName,		typeId	},	
#define MAPEDITFIELDTYPE_END()								};


MAPEDITFIELDTYPE_BEGIN( MAPEDIT_FIELDTYPELIST )
	MAPEDITFIELDTYPE_DECLARE(_T(""),					MAP_FIT_NONE)
	MAPEDITFIELDTYPE_DECLARE(_T("Card"),				MAP_FIT_CARDINFO)
	MAPEDITFIELDTYPE_DECLARE(_T("Holder"),				MAP_FIT_HOLDERINFO)
	MAPEDITFIELDTYPE_DECLARE(_T("Profile"),				MAP_FIT_PROFIL)
	MAPEDITFIELDTYPE_DECLARE(_T("BestContract"),		MAP_FIT_BESTCONTRACT)
	MAPEDITFIELDTYPE_DECLARE(_T("Contract"),			MAP_FIT_CONTRACT)
	MAPEDITFIELDTYPE_DECLARE(_T("Contract Segment"),	MAP_FIT_CONTRACTSEG)
	MAPEDITFIELDTYPE_DECLARE(_T("SpEvent List"),		MAP_FIT_SPECIALEVENTLIST)
	MAPEDITFIELDTYPE_DECLARE(_T("SpEvent"),				MAP_FIT_SPECIALEVENT)
	MAPEDITFIELDTYPE_DECLARE(_T("Event"),				MAP_FIT_EVENT)
	MAPEDITFIELDTYPE_DECLARE(_T("[Israel]VL"),			MAP_FIT_VALIDITY_LOCATION)
	MAPEDITFIELDTYPE_DECLARE(_T("[Intertic] Zone"),		MAP_FIT_INTERTIC_ZONE)
	MAPEDITFIELDTYPE_DECLARE(_T("[NDot] Frame"),		MAP_FIT_NDOT_FRAME)
	MAPEDITFIELDTYPE_DECLARE(_T("[NDot]"),				MAP_FIT_NDOT_FIELDS)
	MAPEDITFIELDTYPE_DECLARE(_T("VixAgentData"),		MAP_FIT_VIXAGENTDATA)
	MAPEDITFIELDTYPE_DECLARE(_T("MK3"),					MAP_FIT_MK3)
	MAPEDITFIELDTYPE_DECLARE(_T("[Atamelang] SpEvent"),	MAP_FIT_SPECIALEVENT_ATAM)
	MAPEDITFIELDTYPE_DECLARE(_T("[Atamelang] Event"),	MAP_FIT_EVENT_ATAM)
MAPEDITFIELDTYPE_END()

#define MAPEDIT_FIELDNAME_LEN	50
typedef struct _MAPEDIT_FIELDINFO {
	TCHAR				name[MAPEDIT_FIELDNAME_LEN];	// nom du champ
//	FIELD_DESCR_EX		fieldInfo;
	FIELD_LOGICALINFO	logicalInfo;
	FIELD_PROPERTY		prop;
} MAPEDIT_FIELDINFO;

typedef MAPEDIT_FIELDINFO			*LPMAPEDIT_FIELDINFO;
typedef CONST MAPEDIT_FIELDINFO		*LPCMAPEDIT_FIELDINFO;

static LPCTSTR MAPEDIT_FIELDNAME_UNKNOWN = _T("INCONNU");

typedef struct {
	const TCHAR* name;
	MAP_FIELDS_ID fieldId;
	FIELD_TYPE	fieldType;
} MAPEDIT_FIELDDESCR;

#define MAPEDITFIELD_BEGIN( mapName )								static MAPEDIT_FIELDDESCR mapName [] = {
#define MAPEDITFIELD_DECLARE( szName,	fieldId,	type )			{szName,	fieldId,	type},	
#define MAPEDITFIELD_END()												};

MAPEDITFIELD_BEGIN( MAPEDIT_FIELDLIST )

	MAPEDITFIELD_DECLARE(	_T("Null"),									MAP_NOID,									TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("Root"),									MAP_ROOT,									TYPE_DATA)

	// champs des informations carte
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_CARDINFO_NULL,							TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvApplicationVersionNumber"),			MAP_CARDINFO_VERSIONNUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvNetworkId"),							MAP_CARDINFO_NETWORKID,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvApplicationIssuerId"),				MAP_CARDINFO_APPISSUERID,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvApplicationValidityEndDate"),		MAP_CARDINFO_APPENDDATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvDataCardPriceAmount"),				MAP_CARDINFO_CAUTION,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderProfiles"),						MAP_CARDINFO_PROFILCOUNT,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] BestContracts"),						MAP_CARDINFO_BESTCONTRACTCOUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] SpecialEvent"),							MAP_CARDINFO_BESTSPECIALEVENTCOUNT,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ICC Date"),								MAP_CARDINFO_ICCDATE,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Card Type"),								MAP_CARDINFO_CARDTYPE,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Mapping Version"),						MAP_CARDINFO_MAPVERSION,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Devise de la caution"),					MAP_CARDINFO_CAUTIONDEVISE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Flag Invalidate"),						MAP_CARDINFO_INVALIDATEFLAG,				TYPE_BOOLEEN)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Flag Telemodification"),					MAP_CARDINFO_TELEMODIFFLAG,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Contract Next Key"),						MAP_CARDINFO_CONTRACTKEY,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Serial Number"),							MAP_CARDINFO_CARDNUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Serial Number (Graphical)"),				MAP_CARDINFO_CARDGRAPHNUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Serial Number (Transcarte)"),			MAP_CARDINFO_TRANSCARDNUMBER,				TYPE_TRANSCARTE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode]EnvData2Version"),						MAP_CARDINFO_DATA2VERSION,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[MifareVix] EnvApplicationVersionNumber"),			MAR_CARDINFO_MIFARE_VERSIONNUMBER,			TYPE_NOMBRE)

	// champs des informations porteur
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_HOLDERINFO_NULL,						TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderIdNumber"),						MAP_HOLDERINFO_IDNUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderBirthDate"),						MAP_HOLDERINFO_BIRTHDATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderDataCardStatus"),					MAP_HOLDERINFO_CARDSTATUS,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderDataCommercialID"),				MAP_HOLDERINFO_COMMERCIALID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderDataSaleDevice"),					MAP_HOLDERINFO_SALEDEVICE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderDataAuthenticator"),				MAP_HOLDERINFO_AUTHENTICATOR,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EnvPayMethod"),							MAP_HOLDERINFO_PAY_METHOD,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderCompany"),						MAP_HOLDERINFO_COMPANY,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Vix] HolderCompanyID"),							MAP_HOLDERINFO_COMPANY_ID,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] HolderLanguage"),							MAP_HOLDERINFO_LANGUAGE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[VixAgent] HolderIdNumber"),						MAR_HOLDERINFO_AGENT_NUMBER,				TYPE_NOMBRE)

	// champs des informations de profil	
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_PROFIL_NULL,							TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderProfileNumber"),					MAP_PROFIL_NUMBER,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] HolderProfileDate"),					MAP_PROFIL_ENDDATE,							TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Start Date"),							MAP_PROFIL_BEGINDATE,						TYPE_DATE)

	// champs des information de BestContracts
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_BESTCONTRACT_NULL,						TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] BestContractTariff (Provider)"),		MAP_BESTCONTRACT_EXPLOITANT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] BestContractTariff (Type)"),			MAP_BESTCONTRACT_TYPE,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] BestContractTariff (Priority)"),		MAP_BESTCONTRACT_PRIORITY,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] BestContractPointer"),					MAP_BESTCONTRACT_INSTANCEPOINTER,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Contract Code"),							MAP_BESTCONTRACT_CONTRACTCODE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Zone"),									MAP_BESTCONTRACT_ZONE,						TYPE_NOMBRE)

	// champs des informations de contrats	
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_CONTRACT_NULL,							TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractProvider"),						MAP_CONTRACT_PROVIDER,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractTariff"),						MAP_CONTRACT_TARIFF,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractSerialNumber"),					MAP_CONTRACT_SERIALNUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractPassengerClass"),				MAP_CONTRACT_PASSENGERCLASS,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSaleAgent"),				MAP_CONTRACT_SALEAGENT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSaleDevice"),				MAP_CONTRACT_SALEDEVICE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractValidityEndDate"),				MAP_CONTRACT_VALIDITYENDDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractStatus"),						MAP_CONTRACT_STATUS,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGreyList"),					MAP_CONTRACT_GREYLIST,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataChrono"),					MAP_CONTRACT_CHRONO,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataFlag"),						MAP_CONTRACT_FLAGTELEMODIF,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Virtual] MappingCode"),							MAP_CONTRACT_CODEMAPPING,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Virtual] MappingType (Ref. BestContract)"),		MAP_CONTRACT_TYPEMAPPING,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Vix] Code Famille"),								MAP_CONTRACT_CODEFAMILLE,					TYPE_NOMBRE)

	// NamedToken
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataTokenNumber1"),				MAP_CONTRACT_TOKENNUMBER1,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataTokenNumber2"),				MAP_CONTRACT_TOKENNUMBER2,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataTokenNumber3"),				MAP_CONTRACT_TOKENNUMBER3,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAutoloadDateStart"),		MAP_CONTRACT_AUTOLOAD_DATESTART,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAutoloadDateStop"),			MAP_CONTRACT_AUTOLOAD_DATESTOP,				TYPE_DATE)

	// Reloading
	MAPEDITFIELD_DECLARE(	_T("[Intertic] Reloading"),								MAP_CONTRACT_COUNTER_RELOADING,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] Counter1"),								MAP_CONTRACT_SECTION_COUNTER1,				TYPE_NOMBRE)
	
	// SoldX
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldX (Counter)"),			MAP_CONTRACT_SOLDX,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataDebitSoldX"),				MAP_CONTRACT_DEBITSOLDX,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldX"),					MAP_CONTRACT_SOLDX_INITIAL,					TYPE_NOMBRE)

	// TPurse
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataTPurse (Counter)"),			MAP_CONTRACT_TPURSE,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataDebitTPurse"),				MAP_CONTRACT_DEBITTPURSE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataTPurse"),					MAP_CONTRACT_TPURSE_INITIAL,				TYPE_NOMBRE)

	// Passenger
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataPassengerTotal"),			MAP_CONTRACT_GROUP,							TYPE_NOMBRE)

	// Z Periodicity
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataEndPeriod"),				MAP_CONTRACT_ENDPERIOD,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldPeriod (Counter)"),		MAP_CONTRACT_SOLDPERIOD,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldPeriod"),				MAP_CONTRACT_TOKENZINITIAL,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Period Type"),							MAP_CONTRACT_TOKENZPERIODTYPE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Period Identity"),						MAP_CONTRACT_PERIODEIDENTITY,				TYPE_NOMBRE)

	// GeoZonales
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone1"),					MAP_CONTRACT_GEOZONE1,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone2"),					MAP_CONTRACT_GEOZONE2,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone3"),					MAP_CONTRACT_GEOZONE3,						TYPE_NOMBRE)

	// GeoSections
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataZones"),					MAP_CONTRACT_ZONES,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldZones (Counter)"),		MAP_CONTRACT_SOLDZONES,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSoldZones"),				MAP_CONTRACT_SOLDZONESINITIAL,				TYPE_NOMBRE)

	// Restriction Hebdo
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataResctrictHebdo"),			MAP_CONTRACT_RESTRICTHEBDO,					TYPE_PLANNING)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractValidityStartDate"),			MAP_CONTRACT_VALIDITYSTARTDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityEndTime"),			MAP_CONTRACT_VALIDITYENDTIME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataToken"),					MAP_CONTRACT_TOKEN,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataIntermodal"),				MAP_CONTRACT_INTERMODAL,					TYPE_NOMBRE)

	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAgentHashPinCode"),			MAP_CONTRACT_HASHPINCODE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAgentRights1"),				MAP_CONTRACT_RIGHTS1,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAgentRights2"),				MAP_CONTRACT_RIGHTS2,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAgentPDCShift"),			MAP_CONTRACT_PDCSHIFT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAgentNumber"),				MAP_CONTRACT_AGENTNUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Contrat Key"),							MAP_CONTRACT_CONTRACTKEY,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Flag Invalidate"),						MAP_CONTRACT_FLAGINVALIDATION,				TYPE_BOOLEEN)

	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityJourneys"),			MAP_CONTRACT_SNCF_VALIDITYJOURNEYS,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyDistance"),			MAP_CONTRACT_SNCF_JOURNEYDISTANCE,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityDuration"),			MAP_CONTRACT_SNCF_VALIDITYDURATION,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityZoneOrigin"),		MAP_CONTRACT_SNCF_VALIDITYZONEORIGIN,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityZoneDestination"),	MAP_CONTRACT_SNCF_VALIDITYZONEDESTINATION,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataPayMethod"),				MAP_CONTRACT_SNCF_PAYMETHOD,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataPriceAmount"),				MAP_CONTRACT_SNCF_PRICEAMOUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSaleDate"),					MAP_CONTRACT_SNCF_SALEDATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataSaleTime"),					MAP_CONTRACT_SNCF_SALETIME,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataLinkedContract"),			MAP_CONTRACT_SNCF_LINKEDCONTRACT,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataReceiptDelivered"),			MAP_CONTRACT_SNCF_RECEIPTDELIVERED,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataScreen"),					MAP_CONTRACT_SNCF_SCREEN,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataException"),				MAP_CONTRACT_SNCF_EXCEPTION,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataProxy"),					MAP_CONTRACT_SNCF_PROXY,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataType"),						MAP_CONTRACT_SNCF_PECTYPE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataRate"),						MAP_CONTRACT_SNCF_PECRATE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataAmount"),					MAP_CONTRACT_SNCF_PECAMOUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataNumber"),					MAP_CONTRACT_SNCF_PECNUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataProxyReversion"),			MAP_CONTRACT_SNCF_PROXYREVERSION,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataVehicleAllowed"),			MAP_CONTRACT_SNCF_VEHICLEALLOWED,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataLimiteDate"),				MAP_CONTRACT_SNCF_LIMITEDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Sncf Validity Journeys Left"),			MAP_CONTRACT_SNCF_VALIDITYJOURNEYSLEFT,		TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Sncf Validity Zones"),					MAP_CONTRACT_SNCF_VALIDITYZONE,				TYPE_NOMBRE)

	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Dernière monté - Arrêt"),				MAP_CONTRACT_EVT_LOCATIONID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Dernière monté - Ligne"),				MAP_CONTRACT_EVT_ROUTENUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Dernière monté - Véhicule"),				MAP_CONTRACT_EVT_VEHICULEID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Dernière monté - Sens"),					MAP_CONTRACT_EVT_SENS,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Corresp. - Nbre Passagers"),				MAP_CONTRACT_EVT_CORSPD_GROUP,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Corresp. - Niveau"),						MAP_CONTRACT_EVT_CORSPD_LEVEL,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Corresp. - Delta Minutes"),				MAP_CONTRACT_EVT_CORSPD_DELTAMIN,			TYPE_NOMBRE)

	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Contrôle ligne sens autorisé"),			MAP_CONTRACT_LINECTRL,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Etat validation PMT"),					MAP_CONTRACT_STATUSPMT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Nb voyage période (Fidélité)"),			MAP_CONTRACT_CPT1VALUE1,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Date début période (Fidélité)"),			MAP_CONTRACT_CPT1DATESTART,					TYPE_DATE)

	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataValidityStartTime"),		MAP_CONTRACT_VALIDITYSTARTTIME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète]  Contrôle d'authenticité"),				MAP_CONTRACT_AUTHENTICATOR,					TYPE_NOMBRE)
	
	MAPEDITFIELD_DECLARE(	_T("[Intercode] CounterValidityEndDate"),				MAP_COUNTER_VALIDITYENDDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] CounterDataValidityEndTime"),			MAP_COUNTER_VALIDITYENDTIME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] CounterContractStatus"),				MAP_COUNTER_STATUS,							TYPE_NOMBRE)

	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataEndInhibitionDate"),		MAP_CONTRAT_DATEENDINIBITION,				TYPE_DATE)

	MAPEDITFIELD_DECLARE(	_T("[Hérault] Intermodal Test"),						MAP_CONTRAT_HERAULT_INTERMODAL_TEST,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Hérault] Intermodal Degrade"),						MAP_CONTRAT_HERAULT_INTERMODAL_DEGRADE,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Hérault] Intermodal Masque"),						MAP_CONTRAT_HERAULT_INTERMODAL_MASQUE,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Hérault] Intermodal Card serial"),					MAP_CONTRAT_HERAULT_INTERMODAL_CARD_SERIAL,	TYPE_NOMBRE)
	
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone32.1"),				MAP_CONTRACT_GEOZONE32_1,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone32.2"),				MAP_CONTRACT_GEOZONE32_2,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone48.1"),				MAP_CONTRACT_GEOZONE48_1,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone48.2"),				MAP_CONTRACT_GEOZONE48_2,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataGeoZone48.3"),				MAP_CONTRACT_GEOZONE48_3,					TYPE_NOMBRE)
	
	MAPEDITFIELD_DECLARE(	_T("[Virtuel] CounterFlag"),							MAP_CONTRACT_HASCOUNTER,					TYPE_BOOLEEN)

	MAPEDITFIELD_DECLARE(	_T("[Intertic] ContractMaxOTP"),						MAP_CONTRAT_CONTRACTMAXOTP,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTPCount (Sold)"),						MAP_CONTRACT_SOLDX_CONSUMED,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTPCount (Reload)"),						MAP_CONTRAT_OTPVALUE,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTPCount"),								MAP_CONTRAT_OTPCOUNT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTPCountZone"),							MAP_CONTRAT_OTPCOUNTZONE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTPValidityEndDate"),					MAP_CONTRAT_OTPVALIDITYENDDATE,				TYPE_DATE)

	MAPEDITFIELD_DECLARE(	_T("[Intertic] CounterContractCount"),					MAP_CONTRAT_COUNTERCONTRACTCOUNT,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] CounterCount"),							MAP_CONTRAT_COUNTERCOUNT,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] CounterCountZone"),						MAP_CONTRAT_COUNTERCOUNTZONE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] CounterValidityEndDate"),				MAP_CONTRAT_COUNTERVALIDITYENDDATE,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] CounterValidityPeriodEndDate"),			MAP_CONTRAT_COUNTERVALIDITYPERIODENDDATE,	TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] ContractMaxCounter"),					MAP_CONTRAT_CONTRACTMAXCOUNTER,				TYPE_NOMBRE)
	
	MAPEDITFIELD_DECLARE(	_T("[Israel] LocationEndList"),							MAP_CONTRACT_VALIDITY_LOCATION_END_LIST,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractVersionNumber"),					MAP_CONTRACT_VERSION_NUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractTariff_Access"),					MAP_CONTRACT_TARIFF_ACCESS,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractTariff_Counter"),					MAP_CONTRACT_TARIFF_COUNTER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractTariff_Name"),						MAP_CONTRACT_TARIFF_NAME,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractSaleNumberDaily"),					MAP_CONTRACT_SALE_NUMBER_DAILY,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractRestrictCode"),					MAP_CONTRACT_RESTRICT_CODE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractRestrictDuration"),				MAP_CONTRACT_RESTRICT_DURATION,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractCustomerProfile"),					MAP_CONTRACT_LINKED_PROFILE_CODE,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("ContractPadding"),									MAP_CONTRACT_PADDING,						TYPE_PADDING)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractTariff"),							MAP_CONTRACT_TARIFF_ISRAEL,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("Priority (Ref BestContract)"),						MAP_CONTRACT_REF_PRIORITY,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractValidityDuration"),				MAP_CONTRACT_VALIDITY_DURATION,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractValidityDurationUnit"),			MAP_CONTRACT_VALIDITY_DURATION_UNIT,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractValidityDurationValue"),			MAP_CONTRACT_VALIDITY_DURATION_VALUE,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractPeriodJourneys"),					MAP_CONTRACT_PERIOD_JOURNEYS,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractPeriodJourneysUnit"),				MAP_CONTRACT_PERIOD_JOURNEYS_UNIT,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractPeriodJourneysValue"),				MAP_CONTRACT_PERIOD_JOURNEYS_VALUE,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractSaleDate"),						MAP_CONTRACT_SALE_DATE,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ContractRestrictTimeCode"),				MAP_CONTRACT_RESTRICT_TIME_CODE,			TYPE_NOMBRE)
	
	// champs des informations de segment de contrat
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyOrigin"),			MAP_CONTRACTSEG_ORIGINE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyDestination"),		MAP_CONTRACTSEG_DESTINATION,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyVia"),				MAP_CONTRACTSEG_VIA,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Journey Destination OR Via"),			MAP_CONTRACTSEG_DESTINATION_OU_VIA,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Journey Destination IF Via"),			MAP_CONTRACTSEG_DESTINATION_SI_VIA,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyLine1"),				MAP_CONTRACTSEG_LIGNEORIGINE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] ContractDataJourneyLine2"),				MAP_CONTRACTSEG_LIGNEDESTINATION,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] Week planning"),						MAP_CONTRACTSEG_PLANNINGHEBDO,				TYPE_PLANNING)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] Sens Force"),							MAP_CONTRACTSEG_SENS_FORCE,					TYPE_BOOLEEN)

	// champs des informations de ValidityLocation
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialLine"),								MAP_CONTRACTSEG_LIGNE,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialRoutesSystem"),						MAP_VALIDITY_LOCATION_ROUTES_SYSTEM,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialZones"),							MAP_VALIDITY_LOCATION_ZONES,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialFareCode"),							MAP_VALIDITY_LOCATION_FARE_CODE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialLinesNumber"),						MAP_VALIDITY_LOCATION_LINES_NUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialRunType"),							MAP_VALIDITY_LOCATION_RUN_TYPE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialRunID"),							MAP_VALIDITY_LOCATION_RUN_ID,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialVehicleCoach"),						MAP_VALIDITY_LOCATION_VEHICLE_COACH,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialSeat"),								MAP_VALIDITY_LOCATION_SEAT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialRoutesSystemFrom"),					MAP_VALIDITY_LOCATION_ROUTES_SYSTEM_FROM,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialRoutesSystemTo"),					MAP_VALIDITY_LOCATION_ROUTES_SYSTEM_TO,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialZonesFrom"),						MAP_VALIDITY_LOCATION_ZONES_FROM,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialZonesTo"),							MAP_VALIDITY_LOCATION_ZONES_TO,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ParkingDataSize"),							MAP_VALIDITY_LOCATION_PARKING_DATA_SIZE,		TYPE_LIST)
	MAPEDITFIELD_DECLARE(	_T("[Israel] ParkingData"),								MAP_VALIDITY_LOCATION_PARKING_DATA,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialContractTypeID"),					MAP_VALIDITY_LOCATION_CONTRACT_TYPE_ID,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialContractTypeID_ETT"),				MAP_VALIDITY_LOCATION_CONTRACT_TYPE_ID_ETT,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialContractTypeID_DEF"),				MAP_VALIDITY_LOCATION_CONTRACT_TYPE_ID_DEF,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] SpatialType"),								MAP_VALIDITY_LOCATION_SPATIAL_TYPE,				TYPE_NOMBRE)

	// champs des informations de la liste des évènements spéciaux
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_SPECIALEVENTLIST_NULL,					TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] SpecialEventProvider"),					MAP_SPECIALEVENTLIST_EXPLOITANT,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] SpecialEventSeriousness"),				MAP_SPECIALEVENTLIST_SERIOUSNESS,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] SpecialEventPointer"),					MAP_SPECIALEVENTLIST_EVENTPOINTER,			TYPE_NOMBRE)

	// champs des informations des évènements spéciaux
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_SPECIALEVENT_NULL,						TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDateStamp"),						MAP_SPECIALEVENT_DATE,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventTimeStamp"),						MAP_SPECIALEVENT_TIME,						TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventResult"),							MAP_SPECIALEVENT_RESULT,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventServiceProvider"),					MAP_SPECIALEVENT_EXPLOITANT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventVehicleId"),						MAP_SPECIALEVENT_VEHICULEID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventContractPointer"),					MAP_SPECIALEVENT_CONTRATPOINTER,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventLocationId"),						MAP_SPECIALEVENT_LOCATIONID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventSerialNumber"),					MAP_SPECIALEVENT_SERIALNUMBER,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDevice"),							MAP_SPECIALEVENT_DEVICE,					TYPE_NOMBRE)

	// champs des informations des évènements
	MAPEDITFIELD_DECLARE(	_T("Null"),												MAP_EVENT_NULL,								TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventBitmap"),							MAP_INTERTIC_EVENTBITMAP,					TYPE_BITMAP)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventCounterBitmap"),					MAP_INTERTIC_EVENTCOUNTBITMAP,				TYPE_BITMAP)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventGeoBitmap"),						MAP_INTERTIC_EVENTGEOBITMAP,				TYPE_BITMAP)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventRouteBitmap"),						MAP_INTERTIC_EVENTROUTEBITMAP,				TYPE_BITMAP)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventValidityBitmap"),					MAP_INTERTIC_EVENTVALIDITYBITMAP,			TYPE_BITMAP)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDateStamp"),						MAP_EVENT_DATE,								TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventTimeStamp"),						MAP_EVENT_TIME,								TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventCode"),							MAP_EVENT_CODE,								TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventResult"),							MAP_EVENT_RESULT,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventServiceProvider"),					MAP_EVENT_EXPLOITANT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDestination"),						MAP_EVENT_DESTINATION,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventLocationId"),						MAP_EVENT_LOCATIONID,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventRouteNumber"),						MAP_EVENT_ROUTENUMBER,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventVehicleId"),						MAP_EVENT_VEHICULEID,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventContractPointer"),					MAP_EVENT_CONTRATPOINTER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDataDateFirstStamp"),				MAP_EVENT_FIRSTJOURNEYDATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDataTimeFirstStamp"),				MAP_EVENT_FIRSTJOURNEYTIME,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventJourneyInterchanges"),				MAP_EVENT_CORRESPONDANCECOUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDataTrip"),						MAP_EVENT_TRONCONSENS,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDataRouteDirection"),				MAP_EVENT_SENS,								TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventSerialNumber"),					MAP_EVENT_SERIALNUMBER,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventJourneyRun"),						MAP_EVENT_JOURNEYRUN,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventTotalJourneys"),					MAP_EVENT_TOTALJOURNEYS,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventPriceAmount"),						MAP_EVENT_PRICEAMOUNT,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intercode] EventDevice"),							MAP_EVENT_DEVICE,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventVersionNumber"),						MAP_EVENT_VERSION_NUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventLine"),								MAP_EVENT_LINE,								TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventStation"),							MAP_EVENT_STATION,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventRunID"),								MAP_EVENT_RUN_ID,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventVehicleCoach"),						MAP_EVENT_VEHICULE_COACH,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventJourneyInterchange"),					MAP_EVENT_JOURNEY_INTERCHANGE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Israel] EventPadding"),							MAP_EVENT_PADDING,							TYPE_PADDING)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] First Stamp Location Id"),				MAP_EVENT_FIRSTJOURNEYLOCALISATION,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Obsolète] Delta Minutes"),							MAP_EVENT_MINUTEDELTA,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventValidityPeriodEndDate"),			MAP_EVENT_VALIDITYPERIODENDDATE,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventValidityTimeFirstStamp"),			MAP_EVENT_VALIDITYTIMEFIRSTSTAMP,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventValidityEndDate"),					MAP_EVENT_VALIDITYENDDATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] EventValidityEndTime"),					MAP_EVENT_VALIDITYENDTIME,					TYPE_DATE)
	
	// Intertic zones
	MAPEDITFIELD_DECLARE(	_T("[Intertic] Distribution"),		MAP_INTERTIC_DISTRIBUTION,		TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] Usage"),				MAP_INTERTIC_USAGE,				TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] OTP"),				MAP_INTERTIC_OTP,				TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[Intertic] Counter"),			MAP_INTERTIC_COUNTER,			TYPE_DATA)

	// NDot Frames
	MAPEDITFIELD_DECLARE(	_T("[NDot] Secure Card Frame"),					MAP_NDOT_SECURE_CARD_FRAME,					TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] Secure Fixed Value Frame"),			MAP_NDOT_SECURE_FIXED_VALUE_FRAME,			TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] Unsecure Variable Value Frame"),		MAP_NDOT_UNSECURED_VARIABLE_VALUE_FRAME,	TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] Unsecure Generic Variable Frame"),	MAP_NDOT_UNSECURED_GENERIC_VARIABLE_FRAME,	TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("EMV infos"),								MAP_EMV_INFOS,								TYPE_DATA)

	// NDot
	MAPEDITFIELD_DECLARE(	_T("[NDot] FrameRevision"),					MAP_NDOT_FRAME_REVISION,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ValueFrameMap"),					MAP_NDOT_VALUE_FRAME_MAP,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] CommuterClassMap"),				MAP_NDOT_COMMUTER_CLASS_MAP,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] CommuterCitizenship"),			MAP_NDOT_COMMUTER_CITIZENSHIP,				TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] CommuterId"),					MAP_NDOT_COMMUTERID,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ValueFrameOperatorId"),			MAP_NDOT_VALUE_FRAME_OPERATOR_ID,			TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] SecureFixedFrameLocation"),		MAP_NDOT_SECURE_FIXED_FRAME_LOCATION,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] UnsecureVariableFrameLocation"),	MAP_NDOT_UNSECURE_VARIABLE_FRAME_LOCATION,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] UnsecureGenericVariableFrameLocation"),	MAP_NDOT_UNSECURE_GENERIC_VARIABLE_FRAME_LOCATION,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] SFIUsageMap"),					MAP_NDOT_SFI_USAGE_MAP,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ProductSpecialEventId"),			MAP_NDOT_PRODUCT_SPECIAL_EVENT_ID,			TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ProductContractCategory"),		MAP_NDOT_PRODUCT_CONTRACT_CATEGORY,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ProductContractId"),				MAP_NDOT_PRODUCT_CONTRACT_ID,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ProductSpecialEventUniqueInstanceId"),MAP_NDOT_SPECIAL_EVENT_UNIQUE_INSTANCE_ID,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] StartDateForFrame"),				MAP_NDOT_START_DATE_FOR_FRAME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] EndDateForFrame"),				MAP_NDOT_END_DATE_FOR_FRAME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] ControlBits"),					MAP_NDOT_CONTROL_BITS,						TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (Control bits) Spare"),			MAP_NDOT_SPARE,								TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (Control bits) DiscountPercent"),MAP_NDOT_DISCOUNT_PERCENT,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] TransactionSequenceId"),			MAP_NDOT_TRANSACTION_SEQUENCEID,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] LastUsageDate"),					MAP_NDOT_LAST_DATE_USAGE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (DailyCounter) DailyInCounter"),	MAP_NDOT_DAILY_IN_COUNTER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (DailyCounter) DailyOutCounter"),MAP_NDOT_DAILY_OUT_COUNTER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (DailyCounter) Spare"),			MAP_NDOT_DAILY_COUNTER_SPARE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (DailyCounter) RemainingValue"),	MAP_NDOT_DAILY_COUNTER_REMAINING_VALUE,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (DailyCounter) RemainingRides"),	MAP_NDOT_DAILY_COUNTER_REMAINING_RIDES,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] MAC"),							MAP_NDOT_MAC,								TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] (Control bits) BlockingStatus"),	MAP_NDOT_BLOCKING_STATUS,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingDateTime"),				MAP_NDOT_BOARDING_DATETIME,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingLocationType"),			MAP_NDOT_BOARDING_LOCATION_TYPE,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingRouteIdFacilityId"),		MAP_NDOT_BOARDING_ROUTEID_FACILITYID,		TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingValueFrame"),			MAP_NDOT_BOARDING_VALUE_FRAME,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingControlBits"),			MAP_NDOT_BOARDING_CONTROL_BITS,				TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] BoardingValidationStatus"),		MAP_NDOT_BOARDING_VALIDATION_STATUS,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] FarePaidSoFarThisJourney"),		MAP_NDOT_FARE_PAID_SOFAR_THIS_JOURNEY,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingDateTime"),				MAP_NDOT_ALIGHTING_DATETIME,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingLocationType"),			MAP_NDOT_ALIGHTING_LOCATION_TYPE,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingRouteIdFacilityId"),	MAP_NDOT_ALIGHTING_ROUTEID_FACILITYID,		TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingValueFrame"),			MAP_NDOT_ALIGHTING_VALUE_FRAME,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingControlBits"),			MAP_NDOT_ALIGHTING_CONTROL_BITS,			TYPE_DATA)
	MAPEDITFIELD_DECLARE(	_T("[NDot] AlightingValidationStatus"),		MAP_NDOT_ALIGHTING_VALIDATION_STATUS,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] LegNumber"),						MAP_NDOT_LEG_NUMBER,						TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] JourneyAdditionalChildCount"),	MAP_NDOT_JOURNEY_ADDITIONAL_CHILD_COUNT,	TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot] TransferAdditionalChildCount"),	MAP_NDOT_TRANSFER_ADDITIONAL_CHILD_COUNT,	TYPE_NOMBRE)
	// NDot Sub fields
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Country"),					MAP_NDOT_SUBFIELD_COUNTRY,				TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Province"),					MAP_NDOT_SUBFIELD_PROVINCE,				TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Municipality type"),		MAP_NDOT_SUBFIELD_MUNICIPALITY_TYPE,	TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Municipality"),				MAP_NDOT_SUBFIELD_MUNICIPALITY,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Operator"),					MAP_NDOT_SUBFIELD_OPERATOR,				TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Stop type"),				MAP_NDOT_SUBFIELD_STOP_TYPE,			TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[NDot subfield] Stop"),						MAP_NDOT_SUBFIELD_STOP,					TYPE_NOMBRE)

	// champs des informations de l'agent VIX
	MAPEDITFIELD_DECLARE(	_T("Null"),										MAP_VIXAGENT_NULL,							TYPE_ANY)
	MAPEDITFIELD_DECLARE(	_T("[VixAgent] HolderRights1"),					MAP_VIXAGENT_HOLDER_RIGTHS_1,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[VixAgent] HolderRights2"),					MAP_VIXAGENT_HOLDER_RIGTHS_2,				TYPE_NOMBRE)

	// EMV Application infos
	MAPEDITFIELD_DECLARE(	_T("[EMV] Provider"),							MAP_EMV_PROVIDER_ID,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Serial number"),						MAP_EMV_SERIAL_NUMBER,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Truncated PAN"),						MAP_EMV_TRUNCATED_PAN,					TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] PAN SN"),								MAP_EMV_PAN_SN,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Application name"),					MAP_EMV_APPLICATION_NAME,				TYPE_TEXTE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Application type"),					MAP_EMV_TYPE,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Effective date"),						MAP_EMV_EFFECTIVE_DATE,					TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[EMV] Expiry date"),						MAP_EMV_EXPIRY_DATE,					TYPE_DATE)

	//Mk3
	MAPEDITFIELD_DECLARE(	_T("[Mk3] ProviderId"),							MAP_MK3_PROVIDER_ID,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] Tariff"),								MAP_MK3_TARIFF,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] ValidityStartDate"),					MAP_MK3_VALIDITYSTARTDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] ValidityEndDate"),					MAP_MK3_VALIDITYENDDATE,				TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] Zones"),								MAP_MK3_ZONES,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] ZonesH"),								MAP_MK3_ZONESH,							TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] JourneyRemmain"),						MAP_MK3_JOURNEY_REMMAIN,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] StoredValue"),						MAP_MK3_STORED_VALUE,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] TransactionValue"),					MAP_MK3_TRANSACTION_VALUE,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] JourneyRemmain1"),					MAP_MK3_JOURNEY_REMMAIN1,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] JourneyRemmain2"),					MAP_MK3_JOURNEY_REMMAIN2,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] JourneyRemmain3"),					MAP_MK3_JOURNEY_REMMAIN3,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] StoredValue1"),						MAP_MK3_STORED_VALUE1,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] StoredValue2"),						MAP_MK3_STORED_VALUE2,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Mk3] StoredValue3"),						MAP_MK3_STORED_VALUE3,					TYPE_NOMBRE)

	// Atamelang Operator card : Special event (Dispatch)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] DispatchDate"),					MAP_SPECIALEVENT_ATAM_DISPATCH_DATE,	TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] DispatchTime"),					MAP_SPECIALEVENT_ATAM_DISPATCH_TIME,	TYPE_DATE)

	// Atamelang Operator card : Event (Dispatch)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftStatus"),					MAP_EVENT_ATAM_SHIFT_STATUS,					TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftFirstOpenDate"),			MAP_EVENT_ATAM_SHIFT_FIRST_OPEN_DATE,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftFirstOpenTime"),			MAP_EVENT_ATAM_SHIFT_FIRST_OPEN_TIME,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastVehiculeId"),			MAP_EVENT_ATAM_SHIFT_LAST_VEHICULE_ID,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastDeviceId"),			MAP_EVENT_ATAM_SHIFT_LAST_DEVICE_ID,			TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastOpenDate"),			MAP_EVENT_ATAM_SHIFT_LAST_OPEN_DATE,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastOpenTime"),			MAP_EVENT_ATAM_SHIFT_LAST_OPEN_TIME,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastCloseDate"),			MAP_EVENT_ATAM_SHIFT_LAST_CLOSE_DATE,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftLastCloseTime"),			MAP_EVENT_ATAM_SHIFT_LAST_CLOSE_TIME,			TYPE_DATE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftSalesCount"),				MAP_EVENT_ATAM_SHIFT_SALES_COUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftSalesAmount"),				MAP_EVENT_ATAM_SHIFT_SALES_AMOUNT,				TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftCancellationsCount"),		MAP_EVENT_ATAM_SHIFT_CANCELLATIONS_COUNT,		TYPE_NOMBRE)
	MAPEDITFIELD_DECLARE(	_T("[Atamelang] ShiftCancellationsAmount"),		MAP_EVENT_ATAM_SHIFT_CANCELLATIONS_AMOUNT,		TYPE_NOMBRE)


MAPEDITFIELD_END()

static const LPCTSTR MAPEDIT_OPLOGICNAME_LIST [CONDITION_OPLOGICAL_COUNT] = {
	_T("ou"),		//	CONDITION_OPLOGICAL_OR
	_T("et"),		//	CONDITION_OPLOGICAL_AND
	_T("nonOu"),	//	CONDITION_OPLOGICAL_NOR
	_T("nonEt"),	//	CONDITION_OPLOGICAL_NAND

};

static const LPCTSTR MAPEDIT_OPCOMPNAME_LIST [CONDITION_OPCOMPARE_COUNT] = {
	_T("="),		//	CONDITION_OPCOMPARE_EQ
	_T("<="),		//	CONDITION_OPCOMPARE_LTE
	_T(">="),		//	CONDITION_OPCOMPARE_GTE
	_T("<"),		//	CONDITION_OPCOMPARE_LT
	_T(">"),		//	CONDITION_OPCOMPARE_GT
	_T("<>"),		//	CONDITION_OPCOMPARE_NEQ
};

#define MAPEDIT_NEEDED_TYPENAME_LEN	50
typedef struct _MAPEDIT_NEEDED_TYPEINFO {
	TCHAR				szName[MAPEDIT_NEEDED_TYPENAME_LEN];	///< Nom du type d'obligation
	MAPFIELDS_IDNEEDED	typeId;								///< Identifiant du type
} MAPEDIT_NEEDED_TYPEINFO;

#define MAPEDIT_NEEDED_TYPE_BEGIN( mapName )					static MAPEDIT_NEEDED_TYPEINFO mapName [] = {
#define MAPEDIT_NEEDED_TYPE_DECLARE( szName,	typeId )			{	szName,		typeId	},	
#define MAPEDIT_NEEDED_TYPE_END()								};

MAPEDIT_NEEDED_TYPE_BEGIN( MAPEDIT_NEEDED_TYPELIST )
	MAPEDIT_NEEDED_TYPE_DECLARE(_T("Non Obligatoire"),						MAPNEEDED_NONEEDED)
	MAPEDIT_NEEDED_TYPE_DECLARE(_T("Actif au calcul du bitmap"),			MAPNEEDED_NEEDEDTOINIT)
	MAPEDIT_NEEDED_TYPE_DECLARE(_T("Toujours accessible"),					MAPNEEDED_NEEDEDTOACCESS)
	MAPEDIT_NEEDED_TYPE_DECLARE(_T("Obligatoire"),							MAPNEEDED_ALLNEEDED)
MAPEDIT_NEEDED_TYPE_END()

#endif /* __MAPDEF_H */